package ch.fhnw.cbip.compiler.enums;

public enum Terminal {
    LPAREN, RPAREN, LBRACE, RBRACE, 
    COMMA, SEMICOLON, COLON, QUESTMARK, EXCLAMARK, 
    MULTOPR, ADDOPR, RELOPR, BECOMES,
    
    LITERAL, IDENT,
    
    PROGRAM, TYPE, CALL, BOOLOPR, NOT, CHANGEMODE, MECHMODE, IF, ELSE, 
    FUN, GLOBAL, LOCAL, FLOWMODE, INIT, PROC, RETURNS,  WHILE,
    SKIP;
}
